# Generated by Django 5.2.1 on 2025-06-03 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_poojabooking_razorpay_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poojabooking',
            name='iyer',
        ),
        migrations.RemoveField(
            model_name='poojabooking',
            name='pooja',
        ),
        migrations.RemoveField(
            model_name='poojabooking',
            name='user',
        ),
        migrations.CreateModel(
            name='RelatedAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='related_advertisement_images/', verbose_name='Banner Image')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Business Category')),
                ('advertised_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
        ),
        migrations.DeleteModel(
            name='IyerProfile',
        ),
        migrations.DeleteModel(
            name='PoojaService',
        ),
        migrations.DeleteModel(
            name='PoojaBooking',
        ),
    ]
