# Generated by Django 5.2.1 on 2025-06-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_poojabooking_iyer_remove_poojabooking_pooja_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatedadvertisement',
            old_name='Category',
            new_name='category',
        ),
    ]
