# Generated by Django 5.2.1 on 2025-06-03 10:58

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_category_relatedadvertisement_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='business_blog_images/', verbose_name='Banner Image')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='tourism_images/', verbose_name='Banner Image')),
                ('content', tinymce.models.HTMLField()),
                ('distance', models.CharField(max_length=255)),
                ('Location', models.TextField(blank=True, null=True, verbose_name='Location')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
