# Generated by Django 5.2.1 on 2025-06-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_businessblog_tourism_business_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessblog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='tourism',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
