# Generated by Django 5.2.1 on 2025-06-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_businessblog_slug_tourism_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessblog',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Business Category'),
        ),
    ]
